
tag_rep_map <- data.frame(
  tag_rep_group = 1:41,
  tag_rep_name = c(
    "RTTP-L",
    "RTTP-L(US)*",
    "RTTP-L(AU)",
    "RTTP-S-3",
    "RTTP-S-4",
    "RTTP-S(PH,ID)-7",
    "RTTP-S(JP)-1*",
    "RTTP-P(JP)-1*",
    "RTTP-P-3*",
    "RTTP-P-8*",
    "RTTP-SA-8",
    "RTTP-SU-8",
    "RTTP-P-7",
    "RTTP-S-7*",
    "RTTP-Z(VN)-7*",
    "PTTP-L",
    "PTTP-L(US)*",
    "PTTP-L(AU)",
    "PTTP-S-3",
    "PTTP-S-4",
    "PTTP-S(PH,ID)-7",
    "PTTP-S(JP)-1*",
    "PTTP-P(JP)-1*",
    "PTTP-P-3*",
    "PTTP-P-8*",
    "PTTP-S-8",
    "PTTP-P-7",
    "PTTP-S-7*",
    "PTTP-Z(VN)-7*",
    "JPTP-L",
    "JPTP-L(US)*",
    "JPTP-L(AU)*",
    "JPTP-S-3*",
    "JPTP-S-4",
    "JPTP-S(PH,ID)-2*",
    "JPTP-S(JP)-1",
    "JPTP-P(JP)-1",
    "JPTP-P-3",
    "JPTP-P-8",
    "JPTP-S-8",
    "JPTP-S-7*"
  ),
  stringsAsFactors = FALSE
)
